---
- name: ZenDotfiles
  hosts: localhost
  connection: local

  roles:
    - role: ghostty
      tags: [ghostty]
    - role: atuin
      tags: [atuin]
    - role: zsh
      tags: [zsh]
    - role: starship
      tags: [starship]
    - role: lazygit
      tags: [lazygit]
