---

- name: "Installing dependencies"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  loop: "{{ lazygit_dependencies }}"

- name: "Installing lazygit"
  community.general.homebrew:
    name: lazygit
    state: present
    update_homebrew: true
