---
- name: "Checking for distribution donfig: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: aerospace_distribution_config

- name: "Run Tasks for distribution: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: aerospace_distribution_config.stat.exists

- name: "Ensure aerospace config directory exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ ansible_facts['user_dir'] }}/.config"
    - "{{ ansible_facts['user_dir'] }}/.config/aerospace"

- name: "Deploy aerospace config"
  ansible.builtin.copy:
    src: aerospace.toml
    dest: "{{ ansible_facts['user_dir'] }}/.config/aerospace"
    mode: "0600"
