---
- name: Installing dependencies for zoxide
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: true
  loop: "{{ zoxide_dependencies }}"

- name: Installing zoxide
  community.general.homebrew:
    name: zoxide
    state: present
    update_homebrew: true
