---
- name: "Checking for distribution config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: zoxide_distribution_config

- name: "Run Tasks for distribution: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: zoxide_distribution_config.stat.exists

- name: "Ensure zoxide load is in .zshrc"
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.zshrc"
    line: eval "$(zoxide init --cmd cd zsh)"
    state: present
    insertafter: EOF
