---
- name: "Installing ZSH"
  community.general.homebrew:
    name: zsh
    state: present
    update_homebrew: true

- name: "Setting ZSH as default shell"
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /opt/homebrew/bin/zsh
  become: true
