---
- name: "Checking for distribution: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: git_distribution_config

- name: "Run distribution specific tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: git_distribution_config.stat.exists

- name: "Ensure git config directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ ansible_facts['user_dir'] }}/.config"
    - "{{ ansible_facts['user_dir'] }}/.config/git"

- name: "Deploy git config"
  ansible.builtin.copy:
    src: config
    mode: "0644"
    dest: "{{ ansible_facts['user_dir'] }}/.config/git/config"

- name: "Ensure git configurtion file path"
  ansible.builtin.lineinfile:
    path: "{{ ansible_facts['user_dir'] }}/.config/zsh/var/var.zsh"
    line: export GIT_CONFIG_GLOBAL="{{ ansible_facts['user_dir'] }}/.config/git/config"
    state: present
    insertafter: EOF
