---
- name: "Install Ghostty"
  community.general.homebrew_cask:
    name: ghostty
    state: present
    update_homebrew: true

- name: "Ensure that config directory exist"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/ghostty"
    state: directory
    mode: "0700"

- name: "Deploy configuration"
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/ghostty/config"
    mode: "0600"
