---
- name: "Checking for distribution config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: tmux_distribution_config

- name: "Run Tasks for distribution: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: tmux_distribution_config.stat.exists

- name: "Ensure tmux config directories exist"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - "{{ ansible_facts['user_dir'] }}/.config"
    - "{{ ansible_facts['user_dir'] }}/.config/tmux"
    - "{{ ansible_facts['user_dir'] }}/.config/tmux/plugins"

- name: "Clone TPM"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/plugins/tpm"
    version: v3.1.0

- name: "Deploy tmux config"
  ansible.builtin.copy:
    src: "files/"
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/"
    mode: "0644"
