### Terminal & Capabilities
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -gq allow-passthrough on

### Indexing & Window Behavior
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

### Key Bindings
set-option -g prefix C-b
set-option -g prefix2 none
setw -g mode-key vi

### Mouse Support
set -g mouse on

### Plugin Settings
set -g @resurrect-capture-pane-contents "on"
set -g @continuum-restore "on"
