### Unbind Defaults
unbind R
unbind %
unbind '"'

### Reload Config
bind R source-file ~/.config/tmux/tmux.conf

### Window & Pane Management
bind w list-windows
bind r command-prompt "rename-window %%"
bind '"' choose-window
bind ^D detach
bind H previous-window
bind L next-window

### Split Panes
bind | split-window -h
bind - split-window -v

### ↔️ Pane Resizing (With Repeat)
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

### Toggle Zoom
bind -r m resize-pane -Z

### Copy Mode Keybindings (Vi-style)
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
