source-file "$HOME/.config/tmux/plugins.conf"
source-file "$HOME/.config/tmux/appearance.conf"
source-file "$HOME/.config/tmux/general.conf"
source-file "$HOME/.config/tmux/keybind.conf"

run '~/.config/tmux/plugins/tpm/tpm'
