---
- name: "Checking for distribution: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_conf

- name: "Run distribution specific tasks: {{ ansiblle_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_conf.stat.exists

- name: "Ensure bat configuration directory exist"
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
  loop:
    - "{{ ansible_user_dir }}/.config/bat"
    - "{{ ansible_user_dir }}/.config/bat/themes"

- name: "Deploy bat config"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: config, dest: "{{ ansible_user_dir }}/.config/bat/config"}
    - { src: tokyonight_storm.tmTheme, dest: "{{ ansible_user_dir }}/.config/bat/themes/tokyonight_storm.tmTheme" }

# REASON: ansible will not see new theme until cache is rebuilt
- name: "Rebuild bat cache"
  ansible.builtin.command: bat cache --build
  args:
    creates: "{{ ansible_user_dir }}/.cache/bat"
